### ISSUE TITLE
Can I ask you something?

### ISSUE THREAD

**Issue by kgm2937** [JPery/MJPEGWriter#10]
Hi, I'm making  Image processing auto-line-tracing vehicle by raspberry-pi.

and, Im beginer of opencv. I tried to find information about that by google, books  etc.

Finally , I found your git . Thank you so much.

I toke the code on my vehicle, and this is the picture,
![image](https://user-images.githubusercontent.com/50862751/58077325-39dda680-7be7-11e9-8481-6670c3e8a383.png)

I want the picture rotate 180 angle and remove  (some?) color correction filter.
(truly, I also want more resolution)
So please give me the way .... THANK YOU

**Comment by JPery** [comment]
This rotate and color correction features are part of OpenCV and no related to the library. You can use cv::rotate function to rotate your image.
