### ISSUE TITLE
Compiling under Ubuntu 18.04

### ISSUE THREAD

**Issue by philipp-schmidt** [JPery/MJPEGWriter#12]
Compiling led to a few undefined references under Ubuntu 18.04. The following might be a better way to compile this if you want to stick to pure g++:

    g++ MJPEGWriter.cpp main.cpp -o MJPEG -lpthread `pkg-config opencv --cflags --libs` -std=c++11

**Comment by JPery** [comment]
This could be due to the OpenCV version rather than Ubuntu version. Which OpenCV version are you using?

**Comment by philipp-schmidt** [comment]
Sorry for replying late.

It's OpenCV 3.2.0 currently. The above command compiles everything just fine, was just letting anyone else know in case they run into the same issue!
