### ISSUE TITLE
Suggested update to `IMWRITE_JPEG_QUALITY`

### ISSUE THREAD

**Issue by evgenyslab** [JPery/MJPEGWriter#13]
https://github.com/JPery/MJPEGWriter/blob/55c0af8765b5575413d5f4aeee095211eea14edb/MJPEGWriter.cpp#L78

I believe def's got updated with cv4+ and do not use the `CV_` prefix anymore.

great code by the way :)

**Comment by JPery** [comment]
I think it'll be better to preserve 'CV_IMWRITE_JPEG_QUALITY' in order to allow compatibility with older OpenCV versions.

Thank you for your comment!
