### ISSUE TITLE
stop() function halting 

### ISSUE THREAD

**Issue by marzxious** [JPery/MJPEGWriter#16]
hi, first thank you for pulling the example together, I've benefited from it a lot as a socket noobie. 
When I ran the example, I was having issue stoping the socket thread on both listens & writes. It seems to stuck at p_thread trying to join the writes & listens. Would you kindly provides some insight ? Thank you.

**Comment by JPery** [comment]
Hi! Thank you for issuing this problem. It seems like the listening thread wasn't exiting as it should so I added a new condition when the sock is invalid to end it. The problem should be fixed at d00cbdc.

Hope this helps.

Best regarads!
