### ISSUE TITLE
Authorisation

### ISSUE THREAD

**Issue by RakshithGB** [JPery/MJPEGWriter#17]
Is there anyway the stream encoded can be authorised with username and password?

**Comment by JPery** [comment]
Hi, @RakshithGB !

I'm thinking about include Basic Authorization. Will it fill your needs?

Best regards!

**Comment by RakshithGB** [comment]
@JPery yes that'll help a lot! Thanks.

**Comment by JPery** [comment]
Hi, @RakshithGB.

You can try 6e143bf, in "Authorization" branch to see if it fit your needs.

Best regards!
