### ISSUE TITLE
Accessing the stream

### ISSUE THREAD

**Issue by alicranck** [JPery/MJPEGWriter#2]
Hi, 
I'm trying to use your code to stream mjpg from a c++ application. The code is running and the server is accepting connections, however I can't seem to access the video (either from the browser or VLC).
Could you specify the exact URL of the stream? Sorry if it's a bit basic...

Thanks!

**Comment by JPery** [comment]
You should have access to the stream via web browser.

The URL is http://ip-address:port/, where "ip-address" is the IP of your machine (or "localhost") and "port" is the port that you give to the constructor of the class. In the example code is 7777.

```C++
MJPEGWriter test(7777);
```

An example URL could be http://localhost:7777/

**Comment by alicranck** [comment]
Thanks for the reply. I guess I have a problem elsewhere since I can't connect there... I'll keep looking

**Comment by JPery** [comment]
Ok, I'm closing this issue for now. Keep me informed, please, so I could help you.

**Comment by alicranck** [comment]
Hey, I got it to work eventually. It was some linux-windows porting issues I guess.  
Thanks again!

**Comment by JPery** [comment]
I haven't tested the code on Windows so it could be the problem. It should work fine in Linux if you want to try
