### ISSUE TITLE
Does this work in chrome?

### ISSUE THREAD

**Issue by ykpark79** [JPery/MJPEGWriter#6]
It works well with vlc player. However chrome only shows first image. Is there any way to test in the browser using img src tag?

**Comment by JPery** [comment]
In fact, this project was created with the intention of stream video to a web browser using the <img> tag. It should work fine if you write <img src="http://your-domain-or-ip:selected-port"/>.

If you can't get it to work in chrome could you try in other web browser to see if it's going fine?

As I told in #2, you should have direct access to the stream via web browser with  http://ip-address:port/

Please tell me if it's working fine.

**Comment by ykpark79** [comment]
Thank you @JPery .
I tried Firefox it works.

I made test html page as below.
```
<html>
<head>
<title>My Web Page</title>
</head>
<body>
<img src="http://localhost:7777">
</body>
</html>
```
When I opened up this page with Chrome, my MJPEG server accepts two clients.
(Note that VLC was just one client)
Then stream freezes.

For the Firefox, it also start with two clients and stream freezes, 
after a few seconds later, one client socket disconnected with "connection reset by peer",
then it started to stream in the browser.

I was wondering why browser is connected as two clients. I think this is causing the issue.
(this might not be an issue of mjpeg server but the browser)

**Comment by JPery** [comment]
I've uploaded a new version where I can read the HTTP headers. With this features Chrome seems to work well. I think that the two clients on Chrome are due to the actual request and some "cache" request. I hope this version works well for you

**Comment by ykpark79** [comment]
Thanks. It works.
But I found another issue.
Regarding recent update, when I want to close application, it waits almost forever in Listener loop.

the way to reproduce is simple.
Run program -> open the web browser  (localhost:7777)
while getting feed stream in the browser, if I turn off the software, it will wait forever.

**Comment by JPery** [comment]
I'll take a look into it.
Thanks!
